### ISSUE TITLE
Different case format for model feilds

### ISSUE THREAD

**Issue by Jerome-Carter** [thomaswsu/trademark-backend#15]
Some model classes use snake case with (_) while others use camel case. This isn't significant, but it is bad practice.

**Comment by henryjeff** [comment]
This is a kinda big deal for me on the frontend w requests. I was operating under the idea that everything would be snake case (bc that's usually the case w python), so if this could be consistent that would be ideal.

**Comment by thomaswsu** [comment]
Resolved?
